version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
      ruby: 2.6
      python: 3.7

  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - SHA=$(git rev-parse HEAD)
      - docker build -t $IMAGE_REPO:$SHA .
  post_build:
    commands:
      - docker tag $IMAGE_REPO:$SHA $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO:$SHA
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO:$SHA