version: 2.1

orbs:
  platform: acornsgrow/platform@1.0.0

workflows:
  build:
    jobs:
      - platform/build_and_push:
          context: techops
          filters:
            branches:
              only: master