version: 2.1

orbs:
  platform: acornsgrow/platform@0.0.4

executors:
  node:
    docker:
      - image: circleci/node:latest

workflows:
  build:
    jobs:
      - platform/create_build:
          context: platform
          filters:
            branches:
              only: master