version: 2
defaults: &defaults
  working_directory: ~/project

build-defaults: &build-defaults
  <<: *defaults
  docker:
    - image: circleci/python:3.6-stretch

jobs:
  
  setup:
    <<: *build-defaults

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli --upgrade
      - run:
          name: Authenticate Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Authenticate AWS ECR
          command: eval $(aws ecr get-login --no-include-email --region us-east-1)
      - run: 
          name: get repo name
          command: export REPO="$(eval echo ${CIRCLE_PROJECT_REPONAME} | tr '[:upper:]' '[:lower:]' | sed 's/[\/-]/_/g')"
      - run: 
          name: echoes
          command: |
            echo ${CIRCLE_PROJECT_REPONAME}
            echo "circle project repo name"
            echo $REPO
            echo "repo"
            echo ${CIRCLE_SHA1}
            echo "sha1"
            echo ${AWS_ACCOUNT_ID}
      - run:
          name: Build Docker Image
          command: |
            docker build -t ${REPO}:${CIRCLE_SHA1} .
            docker tag ${REPO}:${CIRCLE_SHA1} $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/${REPO}:${CIRCLE_SHA1}
      - run:
          name: Push Docker Image to Shipmunk 2
          command: docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/${REPO}:${CIRCLE_SHA1}

workflows:
  version: 2
  build-master:
    jobs:  
      - setup:
          context: techops
          filters:
            branches:
              only: master
              