pipeline:
  dev:
    - name: build 
      type: codebuild
      buildspec: build.yml
    - name: deploy
      type: deployment
      deploymentType: full
  staging:
    - name: build
      type: codebuild
      buildspec: build.yml
    - name: deploy
      type: deployment
      deploymentType: full
  production:
    - name: build
      type: codebuild
      buildspec: build.yml
    - name: deploy
      type: deployment
      deploymentType: full