pipeline:
  dev:
    - name: build 
      type: codebuild
      value: build
    - name: deploy
      type: deployment
      value: full
  staging:
    - name: deploy
      type: deployment
      value: full
  production:
    - name: deploy
      type: deployment
      value: full
